# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestScripttarea3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_scripttarea3(self):
    # Test name: script_tarea3
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://127.0.0.1:8080/")
    # 2 | setWindowSize | 1266x607 | 
    self.driver.set_window_size(1266, 607)
    # 3 | click | id=add-movie | 
    self.driver.find_element(By.ID, "add-movie").click()
    # 4 | click | name=title | 
    self.driver.find_element(By.NAME, "title").click()
    # 5 | type | name=title | Star Wars: Episodio IV
    self.driver.find_element(By.NAME, "title").send_keys("Star Wars: Episodio IV - 2")
    # 6 | click | name=year | 
    self.driver.find_element(By.NAME, "year").click()
    # 7 | type | name=year | 1977
    self.driver.find_element(By.NAME, "year").send_keys("1977")
    # 8 | click | name=director | 
    self.driver.find_element(By.NAME, "director").click()
    # 9 | type | name=director | George Lucas
    self.driver.find_element(By.NAME, "director").send_keys("George Lucas")
    # 10 | type | name=rating | 100
    self.driver.find_element(By.NAME, "rating").send_keys("100")
    # 11 | click | name=review | 
    self.driver.find_element(By.NAME, "review").click()
    # 12 | type | name=review | Muy buena
    self.driver.find_element(By.NAME, "review").send_keys("Muy buena")
    # 13 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 14 | click | id=add-movie | 
    self.driver.find_element(By.ID, "add-movie").click()
    # 15 | click | name=title | 
    self.driver.find_element(By.NAME, "title").click()
    # 16 | click | name=title | 
    self.driver.find_element(By.NAME, "title").click()
    # 17 | type | name=title | Forrest Gump
    self.driver.find_element(By.NAME, "title").send_keys("Forrest Gump - 2")
    # 18 | click | name=year | 
    self.driver.find_element(By.NAME, "year").click()
    # 19 | type | name=year | 1994
    self.driver.find_element(By.NAME, "year").send_keys("1994")
    # 20 | type | name=director | Robert Zemeckis
    self.driver.find_element(By.NAME, "director").send_keys("Robert Zemeckis")
    # 21 | click | name=rating | 
    self.driver.find_element(By.NAME, "rating").click()
    # 22 | type | name=rating | 100
    self.driver.find_element(By.NAME, "rating").send_keys("100")
    # 23 | type | name=review | Muy Buena también
    self.driver.find_element(By.NAME, "review").send_keys("Muy Buena también")
    # 24 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 25 | click | css=.movie:nth-child(2) > .review | 
    self.driver.find_element(By.CSS_SELECTOR, ".movie:nth-child(2) > .review").click()
    # 26 | click | linkText=Dune | 
    self.driver.find_element(By.LINK_TEXT, "Dune").click()
    # 27 | click | css=html | 
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    # 28 | type | name=review | Gran adaptación de una novela clásica de ciencia ficción.
    self.driver.find_element(By.NAME, "review").send_keys("Gran adaptación de una novela clásica de ciencia ficción.2")
    # 29 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 30 | click | css=.movie:nth-child(3) > .review | 
    self.driver.find_element(By.CSS_SELECTOR, ".movie:nth-child(3) > .review").click()
    # 31 | click | linkText=Elvis | 
    self.driver.find_element(By.LINK_TEXT, "Elvis").click()
    # 32 | click | css=html | 
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    # 33 | type | name=review | Hype película biográfica estilizada del Rey
    self.driver.find_element(By.NAME, "review").send_keys("Hype película biográfica estilizada del Rey.2")
    # 34 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
